export const companies = [
    {
        id: 1,
        name: 'PT. Abdi Jaya',
        companyId: 'C0001',
        userCount: 3,
        totalTransaction: 1,
        username: 'theabdijaya',
        location: 'Jl. ABCDE No. 111-114',
        type: 'Restaurant',
        ownershipDocument: 'PT_AbdiJaya_Ownership.pdf',
        companyDocument: 'PT_AbdiJaya_Legality.pdf',
        initialCapital: 'Rp. 2.000.000.000',
        description: 'lorem ipsum',
        user: '1. User A\n2. User B\n3. User C'
    },
    {
        id: 2,
        name: 'PT. Merdeka',
        companyId: 'C0002',
        userCount: 2,
        totalTransaction: 1,
        username: 'ptmerdeka',
        location: 'Jl. Merdeka No. 45',
        type: 'Retail',
        ownershipDocument: 'PT_Merdeka_Ownership.pdf',
        companyDocument: 'PT_Merdeka_Legality.pdf',
        initialCapital: 'Rp. 1.500.000.000',
        description: 'A leading retail company in the country.',
        user: '1. User D\n2. User E'
    },
    {
        id: 3,
        name: 'CV. Maju Selalu',
        companyId: 'C0003',
        userCount: 1,
        totalTransaction: 2,
        username: 'cvmajuselalu',
        location: 'Jl. Maju No. 22',
        type: 'Manufacturing',
        ownershipDocument: 'CV_MajuSelalu_Ownership.pdf',
        companyDocument: 'CV_MajuSelalu_Legality.pdf',
        initialCapital: 'Rp. 3.000.000.000',
        description: 'Specializes in producing high-quality goods.',
        user: '1. User F'
    },
    {
        id: 4,
        name: 'The Wibawa Group',
        companyId: 'C0004',
        userCount: 3,
        totalTransaction: 1,
        username: 'thewibawagroup',
        location: 'Jl. Wibawa No. 8',
        type: 'Consulting',
        ownershipDocument: 'The_WibawaGroup_Ownership.pdf',
        companyDocument: 'The_WibawaGroup_Legality.pdf',
        initialCapital: 'Rp. 4.000.000.000',
        description: 'Providing expert consulting services across various industries.',
        user: '1. User G\n2. User H\n3. User I'
    },
    {
        id: 5,
        name: 'CV. Adiwarna',
        companyId: 'C0005',
        userCount: 2,
        totalTransaction: 0,
        username: 'cvadiwarna',
        location: 'Jl. Adiwarna No. 9',
        type: 'Design',
        ownershipDocument: 'CV_Adiwarna_Ownership.pdf',
        companyDocument: 'CV_Adiwarna_Legality.pdf',
        initialCapital: 'Rp. 1.000.000.000',
        description: 'Creative design agency specializing in branding and digital solutions.',
        user: '1. User J\n2. User K'
    },
    {
        id: 6,
        name: 'PT. HMNS',
        companyId: 'C0006',
        userCount: 2,
        totalTransaction: 2,
        username: 'pthmns',
        location: 'Jl. HMNS No. 2',
        type: 'Tech',
        ownershipDocument: 'PT_HMNS_Ownership.pdf',
        companyDocument: 'PT_HMNS_Legality.pdf',
        initialCapital: 'Rp. 5.000.000.000',
        description: 'Innovative tech company focusing on AI and machine learning.',
        user: '1. User L\n2. User M'
    },
    {
        id: 7,
        name: 'PT. Anda',
        companyId: 'C0007',
        userCount: 1,
        totalTransaction: 0,
        username: 'ptanda',
        location: 'Jl. Anda No. 3',
        type: 'Education',
        ownershipDocument: 'PT_Anda_Ownership.pdf',
        companyDocument: 'PT_Anda_Legality.pdf',
        initialCapital: 'Rp. 2.500.000.000',
        description: 'Leading company in educational services and products.',
        user: '1. User N'
    },
];
