export const verifications = [
    {
        id: 1,
        companyName: 'PT. Mekari',
        name: 'Mikhael Miladeiva',
        username: 'mmldvaaa',
        date: '19 March 2024',
        time: '19:30',
        companyUsername: 'mekari.pt',
        location: 'Jl. YTB No. 85-87',
        type: 'Building',
        ownershipDocument: 'Mekari_Ownership.pdf',
        companyDocument: 'Mekari_Legality.pdf',
        initialCapital: 'Rp. 1.500.000.000',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat doloremque explicabo voluptates expedita natus consequuntur ut, eius, eligendi eos consequatur pariatur enim quos dignissimos ullam. Eaque, odio tempore asperiores cupiditate magni sed cumque libero quibusdam labore sunt voluptatum rem iure similique necessitatibus tempora commodi. Necessitatibus non iusto ex alias reiciendis amet nesciunt. Ducimus necessitatibus inventore quos quis ea, recusandae fuga debitis est quidem et vel, nemo perspiciatis possimus architecto ipsum. Eum eos adipisci laboriosam reprehenderit tempora, iusto illum at ut possimus quidem animi distinctio architecto beatae qui temporibus voluptates. Quia totam dolorem nihil laboriosam velit consequuntur incidunt vel ducimus ea.',
        status: '',
        declineMessage: '',
        class: '',
        field: []
    },
    {
        id: 2,
        companyName: 'Latrust Studio',
        name: 'Enricco Setiawan',
        username: 'enriccoset',
        date: '9 February 2024',
        time: '14:00',
        companyUsername: 'latrust.studio',
        location: 'Jl. Aloha No. 23',
        type: 'Studio',
        ownershipDocument: 'Latrust_Ownership.pdf',
        companyDocument: 'Latrust_Legality.pdf',
        initialCapital: 'Rp. 750.000.000',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat doloremque explicabo voluptates expedita natus consequuntur ut, eius, eligendi eos consequatur pariatur enim quos dignissimos ullam. Eaque, odio tempore asperiores cupiditate magni sed cumque libero quibusdam labore sunt voluptatum rem iure similique necessitatibus tempora commodi. Necessitatibus non iusto ex alias reiciendis amet nesciunt. Ducimus necessitatibus inventore quos quis ea, recusandae fuga debitis est quidem et vel, nemo perspiciatis possimus architecto ipsum. Eum eos adipisci laboriosam reprehenderit tempora, iusto illum at ut possimus quidem animi distinctio architecto beatae qui temporibus voluptates. Quia totam dolorem nihil laboriosam velit consequuntur incidunt vel ducimus ea.',
        status: '',
        declineMessage: '',
        class: '',
        field: []
    },
    {
        id: 3,
        companyName: 'Marco Group',
        name: 'Raphael Marco',
        username: 'raphaelmarco',
        date: '4 February 2024',
        time: '10:00',
        companyUsername: 'marco.group',
        location: 'Jl. Bromo No. 12',
        type: 'Land',
        ownershipDocument: 'Marco_Ownership.pdf',
        companyDocument: 'Marco_Legality.pdf',
        initialCapital: 'Rp. 2.000.000.000',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat doloremque explicabo voluptates expedita natus consequuntur ut, eius, eligendi eos consequatur pariatur enim quos dignissimos ullam. Eaque, odio tempore asperiores cupiditate magni sed cumque libero quibusdam labore sunt voluptatum rem iure similique necessitatibus tempora commodi. Necessitatibus non iusto ex alias reiciendis amet nesciunt. Ducimus necessitatibus inventore quos quis ea, recusandae fuga debitis est quidem et vel, nemo perspiciatis possimus architecto ipsum. Eum eos adipisci laboriosam reprehenderit tempora, iusto illum at ut possimus quidem animi distinctio architecto beatae qui temporibus voluptates. Quia totam dolorem nihil laboriosam velit consequuntur incidunt vel ducimus ea.',
        status: '',
        declineMessage: '',
        class: '',
        field: []
    }
];
